name: Publish Docker image

on:
  push:
    branches: ['main']
jobs:
  push_to_registry:
    name: push docker image
    runs-on: self-hosted
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}


      # - name: Build Docker image and push it to ECR1
      #   id: docker_build
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: pushimage

      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t test:latest .
        env:
          DOCKER_CLI: docker

      - name: push to ecr
        run: |
          docker push ${{ secrets.AWS_REGISTRY_URL }}/docker_ecr:latest
          
          
