name: Publish Docker image

on:
  push:
    branches: ['main']
jobs:
  push_to_registry:
    name: push docker image
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3
        
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yogi7760/test_docker:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          #run: echo " login successfull "

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Use ECR Account in Next Step
        run: |
            echo "ECR Account: ${{ steps.ecr.outputs.account }}"
            
      - name: Push to ECR
        run: |
          docker tag yogi7760/test_docker ${{ steps.ecr.outputs.account }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/yogi7760/test_docker:latest
          #docker push ${{ steps.ecr.outputs.account }}.dkr.ecr. ${{ secrets.AWS_REGION }}.amazonaws.com/docker_ecr/test_docker:latest
          docker push 664334749222.dkr.ecr. ${{ secrets.AWS_REGION }}.amazonaws.com/docker_ecr:latest


          #docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag

      

      

      
